#!/bin/bash

echo "RAM Usage: "
read memory_check
echo "Current Memory Usage: $memory_check"

if [ $memory_check -lt 90  ]; then
echo "Warning Threshold: $memory_check"  | echo mail -s "Warning Threshold" email@mine.com
echo 'Exit Value: 1'
elif [ $memory_check -gt 89 ]; then
echo "Critical Threshold: $memory_check"  | echo mail -s "Critical Threshold" email@mine.com
echo 'Exit Value: 2'
else
echo "Memory usage is in under threshold"
echo 'Exit Value: 0'
fi
